### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by MasterScrat** [misterdev/flatland-marl#4]
Exciting work!

A new Flatland challenge is ongoing: https://www.aicrowd.com/challenges/neurips-2020-flatland-challenge/

I'm one of the organizers, and I'd love to feature your work in our documentation (https://flatland.aicrowd.com/research/top-challenge-solutions.html), both the code here and the Thesis work at https://amslaurea.unibo.it/20412/1/thesis_giulia_cantini.pdf.

Would you be willing to add license information to this repo so participants would be able to build on your current approach?

Cheers,
Florian

**Comment by giulic3** [comment]
Thank you Florian!
The license is now available, you may add our work to the docs, we are happy to possibly help participants in developing new approaches in Flatland. 

You can also find additional info on the code at https://amslaurea.unibo.it/20487/1/farinelli_devid_tesi.pdf, the thesis by @misterdev , but only in Italian.

Giulia
